// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_donkey_air.Models;

#nullable disable

namespace api_donkey_air.Migrations
{
    [DbContext(typeof(DonkeyAirContext))]
    partial class DonkeyAirContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("api_donkey_air.Models.Departure", b =>
                {
                    b.Property<long>("IdDeparture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdDeparture"));

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdDeparture");

                    b.ToTable("Departure");
                });
#pragma warning restore 612, 618
        }
    }
}
